const state = { content: { icons: {}, photos: [], media: [], teachers: { hafiz: [], alim: [] } } };
const $ = (selector) => document.querySelector(selector);
function showStatus(selector, message) { $(selector).textContent = message; }
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, (character) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[character])); }
function renderPhotos() { const grid = $('#admin-photo-grid'); grid.replaceChildren(); state.content.photos.forEach((source, index) => { const wrapper = document.createElement('div'); const image = document.createElement('img'); image.src = source; image.alt = `Фото ${index + 1}`; const remove = document.createElement('button'); remove.className = 'button button-small'; remove.type = 'button'; remove.textContent = 'Убрать'; remove.addEventListener('click', () => { state.content.photos.splice(index, 1); renderPhotos(); }); wrapper.append(image, remove); grid.append(wrapper); }); }
function renderTeachers(group) { const editor = $(`#${group}-editor`); editor.replaceChildren(); state.content.teachers[group].forEach((teacher, index) => { const row = document.createElement('div'); row.className = 'teacher-edit-row'; row.innerHTML = `<input aria-label="Имя устаза" value="${escapeHtml(teacher.name)}"><input aria-label="Предмет устаза" value="${escapeHtml(teacher.subject)}">`; const remove = document.createElement('button'); remove.className = 'button button-small'; remove.type = 'button'; remove.textContent = 'Убрать'; remove.addEventListener('click', () => { state.content.teachers[group].splice(index, 1); renderTeachers(group); }); row.append(remove); editor.append(row); }); }
function collectTeachers(group) { return [...$(`#${group}-editor`).querySelectorAll('.teacher-edit-row')].map((row) => { const inputs = row.querySelectorAll('input'); return { name: inputs[0].value, subject: inputs[1].value }; }); }
async function loadContent() { const response = await fetch('/api/content'); if (!response.ok) throw new Error('Не удалось загрузить настройки.'); state.content = await response.json(); state.content.teachers ||= { hafiz: [], alim: [] }; state.content.media ||= []; $('#about-icon').value = state.content.icons.about || '▧'; $('#teachers-icon').value = state.content.icons.teachers || '♙'; $('#hafiz-icon').value = state.content.icons.hafiz || '♙'; $('#alim-icon').value = state.content.icons.alim || '♙'; $('#benefit1-icon').value = state.content.icons.benefit1 || '✦'; $('#benefit2-icon').value = state.content.icons.benefit2 || '◒'; $('#benefit3-icon').value = state.content.icons.benefit3 || '⌁'; renderPhotos(); renderTeachers('hafiz'); renderTeachers('alim'); renderMedia(); }
async function loadApplications() { const response = await fetch('/api/applications'); if (response.status === 401) { location.href = '/admin/login'; return; } const result = await response.json(); if (!response.ok) throw new Error(result.message); const list = $('#applications-list'); list.replaceChildren(); if (!result.applications.length) { list.textContent = 'Заявок пока нет.'; return; } result.applications.forEach((application) => { const item = document.createElement('article'); item.className = 'application-item'; item.innerHTML = `<div><h3>${escapeHtml(application.studentName)}</h3><p>${escapeHtml(application.guardianName)} · ${escapeHtml(application.phone)}</p><p>${escapeHtml(application.program)} · ${new Date(application.createdAt).toLocaleString('ru-RU')}</p>${application.comment ? `<p>${escapeHtml(application.comment)}</p>` : ''}</div>`; const actions = document.createElement('div'); actions.className = 'application-actions'; ['accepted', 'rejected'].forEach((status) => { const button = document.createElement('button'); button.className = 'button button-small'; button.type = 'button'; button.textContent = status === 'accepted' ? 'Принять' : 'Отклонить'; button.disabled = application.status === status; button.addEventListener('click', () => updateStatus(application.id, status)); actions.append(button); }); const badge = document.createElement('span'); badge.className = `status-badge status-${application.status}`; badge.textContent = { new: 'Новая', accepted: 'Принята', rejected: 'Отклонена' }[application.status]; actions.append(badge); item.append(actions); list.append(item); }); }
async function saveContent(statusSelector, message) { const response = await fetch('/api/admin/content', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ icons:state.content.icons, photos:state.content.photos, media:state.content.media, teachers:state.content.teachers }) }); showStatus(statusSelector, response.ok ? message : 'Не удалось сохранить изменения.'); }
async function updateStatus(id, status) { const response = await fetch(`/api/applications/${id}`, { method:'PATCH', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ status }) }); if (!response.ok) { showStatus('#applications-status', 'Не удалось изменить статус.'); return; } loadApplications(); }
$('#content-form').addEventListener('submit', async (event) => { event.preventDefault(); state.content.icons = { ...state.content.icons, about:$('#about-icon').value, teachers:$('#teachers-icon').value, hafiz:$('#hafiz-icon').value, alim:$('#alim-icon').value, benefit1:$('#benefit1-icon').value, benefit2:$('#benefit2-icon').value, benefit3:$('#benefit3-icon').value }; await saveContent('#content-status', 'Иконки сохранены.'); });
document.querySelectorAll('[data-add-teacher]').forEach((button) => button.addEventListener('click', () => { const group = button.dataset.addTeacher; state.content.teachers[group].push({ name: 'Новый устаз', subject: 'Предмет' }); renderTeachers(group); }));
$('#save-teachers').addEventListener('click', async () => { state.content.teachers.hafiz = collectTeachers('hafiz'); state.content.teachers.alim = collectTeachers('alim'); await saveContent('#teachers-status', 'Список устазов сохранён.'); });
$('#photo-upload').addEventListener('change', async (event) => { const files = [...event.target.files].slice(0, 6 - state.content.photos.length); const uploaded = await Promise.all(files.map(async (file) => { const data = await new Promise((resolve) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.readAsDataURL(file); }); const response = await fetch('/api/admin/upload', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ data }) }); return response.ok ? (await response.json()).path : null; })); state.content.photos = [...state.content.photos, ...uploaded.filter(Boolean)].slice(0, 6); renderPhotos(); });
$('#save-photos').addEventListener('click', () => saveContent('#photo-status', 'Фотографии сохранены.'));
$('#refresh-applications').addEventListener('click', loadApplications);
$('#logout-button').addEventListener('click', async () => { await fetch('/api/admin/logout', { method:'POST' }); location.href = '/admin/login'; });
Promise.all([loadContent(), loadApplications()]).catch((error) => showStatus('#applications-status', error.message));

function renderMedia() {
  const grid = $('#admin-media-grid'); if (!grid) return; grid.replaceChildren();
  state.content.media.forEach((item, index) => {
    const card = document.createElement('article'); card.className = 'admin-media-card';
    const preview = item.type === 'video' ? document.createElement('video') : document.createElement('img');
    preview.src = item.path; preview.muted = true; preview.preload = 'metadata'; if (item.type === 'video') preview.controls = true;
    const title = document.createElement('input'); title.value = item.title || ''; title.placeholder = 'Название истории'; title.maxLength = 80;
    const description = document.createElement('textarea'); description.value = item.description || ''; description.placeholder = 'Короткая подпись'; description.maxLength = 180;
    const remove = document.createElement('button'); remove.className = 'button button-small'; remove.type = 'button'; remove.textContent = 'Убрать';
    title.addEventListener('input', () => { item.title = title.value; }); description.addEventListener('input', () => { item.description = description.value; });
    remove.addEventListener('click', () => { state.content.media.splice(index, 1); renderMedia(); }); card.append(preview, title, description, remove); grid.append(card);
  });
}
function initMediaPanel() {
  const panel = document.createElement('section'); panel.className = 'admin-panel media-admin-panel';
  panel.innerHTML = '<h2>Жизнь медресе</h2><p class="upload-note">Добавляйте истории: фото (JPG, PNG, WebP) и видео (MP4, WebM) до 30 МБ. На сайте будет показано до 12 материалов.</p><input id="media-upload" type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" multiple><div class="admin-media-grid" id="admin-media-grid"></div><button class="button" id="save-media" type="button">Опубликовать ленту</button><p class="form-status" id="media-status" role="status"></p>';
  document.querySelector('.admin-page').insertBefore(panel, document.querySelector('.admin-panel:last-child'));
  $('#media-upload').addEventListener('change', async (event) => {
    const files = [...event.target.files].slice(0, 12 - state.content.media.length); const status = $('#media-status'); status.textContent = 'Загружаем материалы…';
    const uploaded = await Promise.all(files.map(async (file) => {
      if (file.size > 30 * 1024 * 1024) return null;
      const data = await new Promise((resolve) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.readAsDataURL(file); });
      const response = await fetch('/api/admin/upload', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ data }) });
      return response.ok ? { path:(await response.json()).path, type:file.type.startsWith('video/') ? 'video' : 'image', title:'', description:'' } : null;
    }));
    state.content.media = [...state.content.media, ...uploaded.filter(Boolean)].slice(0, 12); renderMedia(); status.textContent = uploaded.some((item) => !item) ? 'Часть файлов не загружена: проверьте формат и размер.' : 'Материалы готовы к публикации.';
  });
  $('#save-media').addEventListener('click', () => saveContent('#media-status', 'Лента опубликована.')); renderMedia();
}
initMediaPanel();
